### ISSUE TITLE
Rework entity API

### ISSUE THREAD

**Issue by Nicolas-Ferre** [modor-engine/modor#166]
**Feature**
Rework the way to create an entity from components.

**Tasks**
- [x] Move `Singleton` associated type from `EntityMainComponent` to `Component` trait
- [x] Add `SingletonComponent` derive macro, that works similarly to `Component` derive macro
- [x] Remove `EntityMainComponent` trait
- [x] Create trait `ComponentSystems` and move `Component::on_update` method in this trait
- [x] Remove `IsEntityMainComponent::IsEntityMainComponent`
- [x] Create `systems` proc macro to implement  `ComponentSystems`
- [x] Create NoSystem derive macro as alternative to `systems` proc macro
- [x] Remove `entity`, `component` and `singleton` proc macro
- [x] Add `with`, ... methods to `EntityBuilder` trait (previously `Built` trait) and remove generic parameter
- [x] Rework `EntityBuilder` to not depend on any main component, and make sure it implements `BuiltEntity` trait
- [x] Adapt `BuiltEntity::with_dependency` method to take singleton component type as generic argument

**Examples**
```rust
fn main() {
    App::new()
        .with_entity(GraphicsModule::build())
        .with_entity(button_material())
        .with_entity(main_menu())
}

fn button_material() -> impl BuiltEntity {
    EntityBuilder::new().with(Material::rectangle("BUTTON_MATERIAL").with_color(Color::GREEN))
}

fn main_menu() -> impl BuiltEntity {
    EntityBuilder::new()
        .with(GridLayout::new(1, 3))
        .with(Transform2D::new())
        .with_child(start_button().with(GridCell::new(0, 0, 1, 2)))
        .with_child(quit_button().with(GridCell::new(0, 2, 1, 2)))
        .with_dependency::<GraphicsModule>(GraphicsModule::build())
}

fn main_menu_button() -> impl BuiltEntity {
    EntityBuilder::new()
        .with(Button::new("BUTTON_MATERIAL"))
        .with(Model::new())
        .with(Transform2D::new())
}

fn start_button() -> impl BuiltEntity {
    main_menu_button()
        .with(Text::new("Start"))
        .with(StartTrigger::default())
}

fn quit_button() -> impl BuiltEntity {
    EntityBuilder::new()
        .with_inherited(main_menu_button())
        .with(Text::new("Quit"))
}

#[derive(Component, Default)]
struct StartTrigger;

#[systems]
impl StartTrigger {
    #[run]
    fn update(button: &Button) {
        if button.is_just_released() {
            println!("Start button pressed");
        }
    }
}
```
