### ISSUE TITLE
Make graphics resource creation safer

### ISSUE THREAD

**Issue by Nicolas-Ferre** [modor-engine/modor#173]
**Problem**
With the current API, it is easy to forget to provide camera key to model, or target key to camera.

**Feature**
Provide safer constructors for graphics resources when relevant. 

**Tasks**
- [x] Add new argument for target key to `Camera2D::new`
- [x] Add method `Camera2D::hidden` to avoid providing a target key
- [x] Add new argument for camera key to `Model::rectangle`
- [x] Add method `Model::hidden_rectangle`   to avoid providing a camera key
