### ISSUE TITLE
Refactor `modor_input` crate

### ISSUE THREAD

**Issue by Nicolas-Ferre** [modor-engine/modor#178]
**Problem**
New version of `modor_graphics` crate has introduced new conventions that have not been yet applied to `modor_input` crate.

**Feature**
Refactor `modor_input` crate to follow the same conventions as `modor_graphics` crate.

**Tasks**
- [ ] Merge all instances of `Finger` into a single `Touch` component
- [ ] Merge all instances of `Gamepad` into a single `Gamepads` component
- [ ] Transfer logic of `InputEventCollector` into `Keyboard`, `Mouse`, `Touch` and `Gamepads` components
- [ ] Remove `InputEventCollector` type
- [ ] Remove `InputModule` type
- [ ] Adapt module tree to follow same tree as `modor_graphics` crate
- [ ] Follow same documentation template as `modor_graphics` crate (sections "Requirements", "Related components", ...)
