### ISSUE TITLE
Refactor `modor_physics` crate

### ISSUE THREAD

**Issue by Nicolas-Ferre** [modor-engine/modor#179]
**Problem**
New version of `modor_graphics` crate has introduced new conventions that have not been yet applied to `modor_physics` crate.

**Feature**
Refactor `modor_physics` crate to follow the same conventions as `modor_graphics` crate.

**Tasks**
- [ ] Replace `CollisionGroupRef` by more lighter ID objects, or use directly components
- [ ] Move logic of GraphicsModule into each dedicated component (`Transform`, `Dynamics2D`, ...)
- [ ] Replace `storages_2d` module by components like for `modor_graphics`
- [ ] Adapt module tree to follow same tree as `modor_graphics` crate
- [ ] Remove or replace `PhysicsModule` type by `module()` function
- [ ] Follow same documentation template as `modor_graphics` crate (sections "Requirements", "Related components", ...)
