### ISSUE TITLE
Improve EntityBuilder API

### ISSUE THREAD

**Issue by Nicolas-Ferre** [modor-engine/modor#182]
**Problem**
The current `EntityBuilder` API leads sometimes to undesired formatting due to too long definition of components.

**Feature**
Improve `EntityBuilder` API by making it more "flat".

**Examples**
Current version:
```Rust
fn object() -> impl BuiltEntity {
    EntityBuilder::new()
        .with(
            Transform2D::new()
                .with_position(Vec2::new(0.15, 0.15))
                .with_size(Vec2::new(0.25, 0.5)),
        )
        .with(Dynamics2D::new().with_angular_velocity(FRAC_PI_2))
        .with(Model::rectangle(MaterialKey::Object).with_camera_key(CameraKey))
        .with_child(child())
}
```

New version:
```rust
fn object2() -> impl BuiltEntity {
    EntityBuilder::new()
        .component(Transform2D::new())
        .with(|c| c.position = Vec2::new(0.15, 0.15))
        .with(|c| c.size = Vec2::new(0.25, 0.5))
        .component(Dynamics2D::new())
        .with(|c| c.angular_velocity = FRAC_PI_2)
        .component(Model::rectangle(MaterialKey::Object).with_camera_key(CameraKey))
        .with(|c| c.camera_keys.push(CameraKey.into_key()))
        .child(child())
}
```

**Tasks**
- [ ] Rename `EntityBuilder` methods so that `with_` prefixes disapear (`with` method will become `component`)
- [ ] Add `EntityComponentBuilder<C>: BuiltEntity` type with method `with(impl FnOnce(&mut C))`
- [ ] Change returned type of `EntityBuilder::component` to `EntityComponentBuilder`
- [ ] Remove all `with_` methods of component types
