### ISSUE TITLE
Make graphics module more flexible

### ISSUE THREAD

**Issue by Nicolas-Ferre** [modor-engine/modor#266]
**Problem**
#264 cannot be implemented independently to the graphics module internals.
As it could be possible to duplicate resources like textures or shaders and configure the duplicated resource for picking, it's not great in term of architecture and this is a lot of copy-paste.
Making the graphics module more flexible would: 
- allow to implement picking as a layer on top of the graphics module
- allow to implement more easily features like shadows
- allow user to create more complex graphics workflows 

**Feature**
Make graphics module more flexible.

**Tasks**
- [x] (1) Add dynamic filters for `Query` to be able to do `query.with_filter(filter)` where filter is an instance of `QueryFilter` (https://github.com/modor-engine/modor/pull/267)
- [x] Allow `TextureBuffer` to only retrieve specific pixels to avoid retrieving the whole texture (https://github.com/modor-engine/modor/pull/274)
- [x] (3) Replace Model by `InstanceGroup2D` and `InstanceRendering2D` **[after 1]** (https://github.com/modor-engine/modor/pull/268)
- [x] (4) Add custom Material **[after 6]** (https://github.com/modor-engine/modor/pull/271)
- [x] (6) Add custom Shader **[after 3]** (https://github.com/modor-engine/modor/pull/270)
- [x] (5) Add method to `InstanceGroup2D` to register custom instance buffers **[after 4]** (https://github.com/modor-engine/modor/pull/272)
- [x] Add dedicated material for texts **[after 5]** (https://github.com/modor-engine/modor/pull/273)
- [x] Activate multisampling only for specific `Shader`/`RenderTarget` **[after 5]** (https://github.com/modor-engine/modor/pull/275)
- [x] Add `Shader` field to configure whether alpha channel is replaced at each new instance drawn (like RGB channels) or not (like standard use of alpha channel) **[after 5]** (https://github.com/modor-engine/modor/pull/276)
- [x] Add `RenderMode` resource type to easily identify `InstanceRendering2D`s (main, picking, shadows, ...) **[after 5]** (https://github.com/modor-engine/modor/pull/277)

**Notes**
- For custom materials, we cannot make `Material` generic because of resource key. Instead, a material can be defined as an entity having 2 components:
    - `Material`, that contains internally the resource key and the GPU uniform/binding group.
    - A custom component that would update `Material` with custom data.
- Once everything will be implementing, it should be able to implement picking the following way for all resources used by the normal rendering mode:
    - All `RenderTarget`s will be "cloned" in the picking module.
    - All `Camera2D` will be "cloned" in the picking module.
    - All `Texture`s with a `RenderTarget` will be "cloned" in the picking module.
    - All `Window`s with a `RenderTarget` will be "cloned" as a `Texture` in the picking module.
    - All `Material`s will be "cloned" in the picking module if a material converter to a picking material is defined. If not, then the material will be replaced by the default picking material.
    - All `InstanceRendering2D` willl be "cloned" in the picking module and reconfigured for the picking.
- Multi-sampling must not be used for picking to avoid introducing "invalid" colors.

**Examples**
```rust
fn simple_rectangle() -> impl EntityBuilder {
    const INSTANCE_GROUP: ResKey<InstanceGroup2D> = ResKey::unique("simple-rectangle");
    const MATERIAL: ResKey<Material> = ResKey::unique("simple-rectangle");
    EntityBuilder::new()
        .component(Transform2D::new())
        .component(ZIndex::from(2))
        .component(InstanceGroup2D::from_self(INSTANCE_GROUP))
        .component(InstanceRendering2D::new(
            INSTANCE_GROUP,
            DEFAULT_CAMERA,
            MATERIAL,
        ))
        .inherited(default_material(MATERIAL))
}

#[derive(Component, NoSystem)]
struct Instance;

fn instance(position: Vec2) -> impl EntityBuilder {
    EntityBuilder::new()
        .component(Instance)
        .component(Transform2D::new())
        .with(|t| t.position = position)
        .component(ZIndex::from(1))
}

fn instances() -> impl EntityBuilder {
    const INSTANCE_GROUP: ResKey<InstanceGroup2D> = ResKey::unique("instances");
    const DEFAULT_MATERIAL: ResKey<Material> = ResKey::unique("rectangle-instances");
    const ELLIPSE_MATERIAL: ResKey<Material> = ResKey::unique("ellipse-instances");
    EntityBuilder::new()
        .component(InstanceGroup2D::from_filter(DynEntityFilter::new::<With<Instance>>()))
        .component(InstanceRendering2D::new(
            INSTANCE_GROUP,
            DEFAULT_CAMERA,
            MATERIAL,
        ))
        .component(InstanceRendering2D::new(
            INSTANCE_GROUP,
            SECONDARY_CAMERA,
            ELLIPSE_MATERIAL,
        ))
        .child_entity(default_material(DEFAULT_MATERIAL))
        .child_entity(ellipse_material(ELLIPSE_MATERIAL))
        .child_entity(instance(Vec2::new(0.5, 0.2)))
        .child_entity(instance(Vec2::new(0.4, 0.3)))
        .child_entity(instance(Vec2::new(0.1, 0.7)))
}
```
