### ISSUE TITLE
Implement new API

### ISSUE THREAD

**Issue by Nicolas-Ferre** [modor-engine/modor#311]
**Feature**
Implements version 2 of #280, but by limiting the amount of duplicated data (e.g. the `Glob`s and node local data).

**Tasks**
- [ ] Add new version of `modor`
- [ ] Add new version of `modor_derive`
- [ ] Add new version of `modor_math`
- [ ] Add new version of `modor_jobs`
- [ ] Add new version of `modor_physics`
- [ ] Add new version of `modor_input`
- [ ] Add new version of `modor_resources`
- [ ] Add new version of `modor_graphics`
- [ ] Add `ModelMapper` to derivate a set of models dynamically (for picking, shadow maps, ...)
- [ ] Add `is_main_rendering` field for the `Target`
