### ISSUE TITLE
Improve new API

### ISSUE THREAD

**Issue by Nicolas-Ferre** [modor-engine/modor#312]
**Feature**
Improve the new API:
- Use `App` everywhere instead of `Context` for more flexibility
- Avoid splitting data between local node and glob, and instead put everything on glob side
- Ensure valid state at any time by applying full glob update each time a glob field is modified

**Tasks**

- [ ] Replace `Context` by `App` everywhere
- [ ] Add `FromApp` and enforce it for all globs
- [ ] Update `modor/glob.rs` module with new version from branch 311
- [ ] Add `GlobUpdater` trait, utils and macro
- [ ] Remove generic type from `App::new`
- [ ] Add `App::take` and `RootNodeHandle::take` + simplify some node updates in graphics crate
- [ ] Remove `Visit` and `Const` and do inner updates manually
- [ ] Replace `RootNode`/`Node` by `FromApp`/`Singleton` (init + update methods) + remove any notion of "node"
- [ ] Make `Body2D` a glob and implements GlobUpdater
- [ ] Make `CollisionGroup` a glob and implements GlobUpdater
- [ ] Make ... a glob a glob and implements GlobUpdater
- [ ] Perform last global cleanup/refactoring if necessary
